# docker-compose up -d
# docker-compose stop
version: "3.9"
services:
  db:
    image: postgres
    container_name: hacs-db
    environment:
      - POSTGRES_DATABASE=hcs_system_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    #restart: always
